using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DLECalibrationToolV2.PI_AFSDK
{
    /// <summary>
    /// Constants class to define PI tags for each panel- PI tags to store data for Lux and CCT, PI Tag to store user comments after running each panel and PI Tags to store comments when user clicks on stop button. 
    /// The PI point tags are stored in List based on panel and measurement locaton.
    /// </summary>
    class PITags
    {
        #region List to store PI Tags for the panel
        private static List<string> panel1Left = new List<string>();
        private static List<string> panel1Right = new List<string>();
        private static List<string> panel2Left = new List<string>();
        private static List<string> panel2Right = new List<string>();
        private static List<string> panel3Left = new List<string>();
        private static List<string> panel3Right = new List<string>();
        private static List<string> panel4Left = new List<string>();
        private static List<string> panel4Right = new List<string>();
        private static List<string> panel5Left = new List<string>();
        private static List<string> panel5Right = new List<string>();
        private static List<string> panel6Left = new List<string>();
        private static List<string> panel6Right = new List<string>();
        private static List<string> panel7Left = new List<string>();
        private static List<string> panel7Right = new List<string>();
        private static List<string> panel8Left = new List<string>();
        private static List<string> panel8Right = new List<string>();
        #endregion


        #region Variable to store PI Tags
        public static string user_commentsTag = "";
        public static string stop_session_commentsTag = "";

        private static string[] PANEL1_MPT1_WARM_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL1.MPT1.WARM.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL1.MPT1.WARM.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL1_MPT1_WARM_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL1.MPT1.WARM.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL1.MPT1.WARM.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL1_MPT1_WARM_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL1.MPT1.WARM.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL1.MPT1.WARM.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL1_MPT1_WARM_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL1.MPT1.WARM.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL1.MPT1.WARM.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL1_MPT1_WARM_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL1.MPT1.WARM.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL1.MPT1.WARM.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL1_MPT1_WARM_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL1.MPT1.WARM.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL1.MPT1.WARM.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL1_MPT1_WARM_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL1.MPT1.WARM.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL1.MPT1.WARM.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL1_MPT1_WARM_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL1.MPT1.WARM.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL1.MPT1.WARM.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL1_MPT1_WARM_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL1.MPT1.WARM.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL1.MPT1.WARM.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL1_MPT1_COOL_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL1.MPT1.COOL.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL1.MPT1.COOL.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL1_MPT1_COOL_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL1.MPT1.COOL.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL1.MPT1.COOL.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL1_MPT1_COOL_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL1.MPT1.COOL.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL1.MPT1.COOL.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL1_MPT1_COOL_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL1.MPT1.COOL.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL1.MPT1.COOL.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL1_MPT1_COOL_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL1.MPT1.COOL.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL1.MPT1.COOL.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL1_MPT1_COOL_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL1.MPT1.COOL.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL1.MPT1.COOL.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL1_MPT1_COOL_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL1.MPT1.COOL.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL1.MPT1.COOL.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL1_MPT1_COOL_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL1.MPT1.COOL.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL1.MPT1.COOL.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL1_MPT1_COOL_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL1.MPT1.COOL.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL1.MPT1.COOL.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL1_MPT1_COMBINED_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL1.MPT1.COMBINED.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL1.MPT1.COMBINED.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL1_MPT1_COMBINED_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL1.MPT1.COMBINED.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL1.MPT1.COMBINED.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL1_MPT1_COMBINED_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL1.MPT1.COMBINED.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL1.MPT1.COMBINED.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL1_MPT2_WARM_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL1.MPT2.WARM.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL1.MPT2.WARM.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL1_MPT2_WARM_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL1.MPT2.WARM.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL1.MPT2.WARM.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL1_MPT2_WARM_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL1.MPT2.WARM.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL1.MPT2.WARM.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL1_MPT2_WARM_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL1.MPT2.WARM.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL1.MPT2.WARM.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL1_MPT2_WARM_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL1.MPT2.WARM.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL1.MPT2.WARM.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL1_MPT2_WARM_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL1.MPT2.WARM.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL1.MPT2.WARM.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL1_MPT2_WARM_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL1.MPT2.WARM.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL1.MPT2.WARM.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL1_MPT2_WARM_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL1.MPT2.WARM.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL1.MPT2.WARM.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL1_MPT2_WARM_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL1.MPT2.WARM.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL1.MPT2.WARM.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL1_MPT2_COOL_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL1.MPT2.COOL.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL1.MPT2.COOL.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL1_MPT2_COOL_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL1.MPT2.COOL.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL1.MPT2.COOL.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL1_MPT2_COOL_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL1.MPT2.COOL.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL1.MPT2.COOL.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL1_MPT2_COOL_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL1.MPT2.COOL.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL1.MPT2.COOL.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL1_MPT2_COOL_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL1.MPT2.COOL.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL1.MPT2.COOL.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL1_MPT2_COOL_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL1.MPT2.COOL.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL1.MPT2.COOL.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL1_MPT2_COOL_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL1.MPT2.COOL.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL1.MPT2.COOL.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL1_MPT2_COOL_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL1.MPT2.COOL.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL1.MPT2.COOL.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL1_MPT2_COOL_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL1.MPT2.COOL.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL1.MPT2.COOL.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL1_MPT2_COMBINED_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL1.MPT2.COMBINED.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL1.MPT2.COMBINED.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL1_MPT2_COMBINED_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL1.MPT2.COMBINED.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL1.MPT2.COMBINED.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL1_MPT2_COMBINED_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL1.MPT2.COMBINED.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL1.MPT2.COMBINED.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL2_MPT1_WARM_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL2.MPT1.WARM.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL2.MPT1.WARM.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL2_MPT1_WARM_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL2.MPT1.WARM.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL2.MPT1.WARM.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL2_MPT1_WARM_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL2.MPT1.WARM.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL2.MPT1.WARM.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL2_MPT1_WARM_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL2.MPT1.WARM.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL2.MPT1.WARM.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL2_MPT1_WARM_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL2.MPT1.WARM.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL2.MPT1.WARM.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL2_MPT1_WARM_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL2.MPT1.WARM.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL2.MPT1.WARM.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL2_MPT1_WARM_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL2.MPT1.WARM.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL2.MPT1.WARM.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL2_MPT1_WARM_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL2.MPT1.WARM.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL2.MPT1.WARM.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL2_MPT1_WARM_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL2.MPT1.WARM.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL2.MPT1.WARM.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL2_MPT1_COOL_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL2.MPT1.COOL.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL2.MPT1.COOL.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL2_MPT1_COOL_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL2.MPT1.COOL.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL2.MPT1.COOL.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL2_MPT1_COOL_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL2.MPT1.COOL.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL2.MPT1.COOL.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL2_MPT1_COOL_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL2.MPT1.COOL.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL2.MPT1.COOL.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL2_MPT1_COOL_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL2.MPT1.COOL.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL2.MPT1.COOL.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL2_MPT1_COOL_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL2.MPT1.COOL.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL2.MPT1.COOL.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL2_MPT1_COOL_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL2.MPT1.COOL.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL2.MPT1.COOL.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL2_MPT1_COOL_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL2.MPT1.COOL.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL2.MPT1.COOL.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL2_MPT1_COOL_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL2.MPT1.COOL.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL2.MPT1.COOL.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL2_MPT1_COMBINED_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL2.MPT1.COMBINED.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL2.MPT1.COMBINED.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL2_MPT1_COMBINED_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL2.MPT1.COMBINED.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL2.MPT1.COMBINED.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL2_MPT1_COMBINED_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL2.MPT1.COMBINED.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL2.MPT1.COMBINED.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL2_MPT2_WARM_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL2.MPT2.WARM.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL2.MPT2.WARM.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL2_MPT2_WARM_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL2.MPT2.WARM.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL2.MPT2.WARM.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL2_MPT2_WARM_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL2.MPT2.WARM.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL2.MPT2.WARM.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL2_MPT2_WARM_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL2.MPT2.WARM.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL2.MPT2.WARM.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL2_MPT2_WARM_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL2.MPT2.WARM.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL2.MPT2.WARM.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL2_MPT2_WARM_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL2.MPT2.WARM.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL2.MPT2.WARM.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL2_MPT2_WARM_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL2.MPT2.WARM.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL2.MPT2.WARM.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL2_MPT2_WARM_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL2.MPT2.WARM.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL2.MPT2.WARM.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL2_MPT2_WARM_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL2.MPT2.WARM.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL2.MPT2.WARM.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL2_MPT2_COOL_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL2.MPT2.COOL.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL2.MPT2.COOL.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL2_MPT2_COOL_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL2.MPT2.COOL.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL2.MPT2.COOL.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL2_MPT2_COOL_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL2.MPT2.COOL.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL2.MPT2.COOL.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL2_MPT2_COOL_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL2.MPT2.COOL.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL2.MPT2.COOL.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL2_MPT2_COOL_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL2.MPT2.COOL.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL2.MPT2.COOL.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL2_MPT2_COOL_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL2.MPT2.COOL.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL2.MPT2.COOL.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL2_MPT2_COOL_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL2.MPT2.COOL.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL2.MPT2.COOL.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL2_MPT2_COOL_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL2.MPT2.COOL.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL2.MPT2.COOL.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL2_MPT2_COOL_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL2.MPT2.COOL.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL2.MPT2.COOL.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL2_MPT2_COMBINED_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL2.MPT2.COMBINED.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL2.MPT2.COMBINED.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL2_MPT2_COMBINED_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL2.MPT2.COMBINED.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL2.MPT2.COMBINED.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL2_MPT2_COMBINED_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL2.MPT2.COMBINED.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL2.MPT2.COMBINED.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL3_MPT1_WARM_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL3.MPT1.WARM.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL3.MPT1.WARM.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL3_MPT1_WARM_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL3.MPT1.WARM.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL3.MPT1.WARM.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL3_MPT1_WARM_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL3.MPT1.WARM.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL3.MPT1.WARM.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL3_MPT1_WARM_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL3.MPT1.WARM.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL3.MPT1.WARM.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL3_MPT1_WARM_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL3.MPT1.WARM.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL3.MPT1.WARM.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL3_MPT1_WARM_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL3.MPT1.WARM.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL3.MPT1.WARM.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL3_MPT1_WARM_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL3.MPT1.WARM.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL3.MPT1.WARM.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL3_MPT1_WARM_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL3.MPT1.WARM.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL3.MPT1.WARM.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL3_MPT1_WARM_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL3.MPT1.WARM.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL3.MPT1.WARM.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL3_MPT1_COOL_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL3.MPT1.COOL.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL3.MPT1.COOL.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL3_MPT1_COOL_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL3.MPT1.COOL.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL3.MPT1.COOL.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL3_MPT1_COOL_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL3.MPT1.COOL.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL3.MPT1.COOL.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL3_MPT1_COOL_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL3.MPT1.COOL.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL3.MPT1.COOL.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL3_MPT1_COOL_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL3.MPT1.COOL.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL3.MPT1.COOL.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL3_MPT1_COOL_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL3.MPT1.COOL.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL3.MPT1.COOL.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL3_MPT1_COOL_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL3.MPT1.COOL.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL3.MPT1.COOL.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL3_MPT1_COOL_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL3.MPT1.COOL.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL3.MPT1.COOL.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL3_MPT1_COOL_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL3.MPT1.COOL.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL3.MPT1.COOL.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL3_MPT1_COMBINED_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL3.MPT1.COMBINED.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL3.MPT1.COMBINED.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL3_MPT1_COMBINED_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL3.MPT1.COMBINED.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL3.MPT1.COMBINED.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL3_MPT1_COMBINED_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL3.MPT1.COMBINED.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL3.MPT1.COMBINED.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL3_MPT2_WARM_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL3.MPT2.WARM.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL3.MPT2.WARM.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL3_MPT2_WARM_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL3.MPT2.WARM.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL3.MPT2.WARM.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL3_MPT2_WARM_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL3.MPT2.WARM.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL3.MPT2.WARM.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL3_MPT2_WARM_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL3.MPT2.WARM.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL3.MPT2.WARM.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL3_MPT2_WARM_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL3.MPT2.WARM.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL3.MPT2.WARM.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL3_MPT2_WARM_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL3.MPT2.WARM.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL3.MPT2.WARM.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL3_MPT2_WARM_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL3.MPT2.WARM.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL3.MPT2.WARM.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL3_MPT2_WARM_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL3.MPT2.WARM.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL3.MPT2.WARM.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL3_MPT2_WARM_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL3.MPT2.WARM.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL3.MPT2.WARM.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL3_MPT2_COOL_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL3.MPT2.COOL.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL3.MPT2.COOL.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL3_MPT2_COOL_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL3.MPT2.COOL.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL3.MPT2.COOL.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL3_MPT2_COOL_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL3.MPT2.COOL.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL3.MPT2.COOL.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL3_MPT2_COOL_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL3.MPT2.COOL.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL3.MPT2.COOL.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL3_MPT2_COOL_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL3.MPT2.COOL.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL3.MPT2.COOL.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL3_MPT2_COOL_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL3.MPT2.COOL.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL3.MPT2.COOL.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL3_MPT2_COOL_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL3.MPT2.COOL.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL3.MPT2.COOL.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL3_MPT2_COOL_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL3.MPT2.COOL.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL3.MPT2.COOL.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL3_MPT2_COOL_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL3.MPT2.COOL.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL3.MPT2.COOL.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL3_MPT2_COMBINED_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL3.MPT2.COMBINED.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL3.MPT2.COMBINED.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL3_MPT2_COMBINED_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL3.MPT2.COMBINED.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL3.MPT2.COMBINED.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL3_MPT2_COMBINED_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL3.MPT2.COMBINED.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL3.MPT2.COMBINED.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL4_MPT1_WARM_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL4.MPT1.WARM.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL4.MPT1.WARM.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL4_MPT1_WARM_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL4.MPT1.WARM.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL4.MPT1.WARM.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL4_MPT1_WARM_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL4.MPT1.WARM.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL4.MPT1.WARM.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL4_MPT1_WARM_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL4.MPT1.WARM.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL4.MPT1.WARM.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL4_MPT1_WARM_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL4.MPT1.WARM.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL4.MPT1.WARM.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL4_MPT1_WARM_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL4.MPT1.WARM.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL4.MPT1.WARM.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL4_MPT1_WARM_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL4.MPT1.WARM.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL4.MPT1.WARM.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL4_MPT1_WARM_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL4.MPT1.WARM.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL4.MPT1.WARM.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL4_MPT1_WARM_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL4.MPT1.WARM.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL4.MPT1.WARM.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL4_MPT1_COOL_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL4.MPT1.COOL.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL4.MPT1.COOL.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL4_MPT1_COOL_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL4.MPT1.COOL.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL4.MPT1.COOL.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL4_MPT1_COOL_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL4.MPT1.COOL.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL4.MPT1.COOL.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL4_MPT1_COOL_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL4.MPT1.COOL.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL4.MPT1.COOL.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL4_MPT1_COOL_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL4.MPT1.COOL.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL4.MPT1.COOL.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL4_MPT1_COOL_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL4.MPT1.COOL.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL4.MPT1.COOL.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL4_MPT1_COOL_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL4.MPT1.COOL.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL4.MPT1.COOL.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL4_MPT1_COOL_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL4.MPT1.COOL.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL4.MPT1.COOL.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL4_MPT1_COOL_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL4.MPT1.COOL.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL4.MPT1.COOL.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL4_MPT1_COMBINED_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL4.MPT1.COMBINED.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL4.MPT1.COMBINED.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL4_MPT1_COMBINED_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL4.MPT1.COMBINED.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL4.MPT1.COMBINED.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL4_MPT1_COMBINED_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL4.MPT1.COMBINED.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL4.MPT1.COMBINED.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL4_MPT2_WARM_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL4.MPT2.WARM.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL4.MPT2.WARM.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL4_MPT2_WARM_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL4.MPT2.WARM.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL4.MPT2.WARM.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL4_MPT2_WARM_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL4.MPT2.WARM.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL4.MPT2.WARM.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL4_MPT2_WARM_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL4.MPT2.WARM.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL4.MPT2.WARM.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL4_MPT2_WARM_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL4.MPT2.WARM.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL4.MPT2.WARM.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL4_MPT2_WARM_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL4.MPT2.WARM.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL4.MPT2.WARM.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL4_MPT2_WARM_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL4.MPT2.WARM.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL4.MPT2.WARM.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL4_MPT2_WARM_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL4.MPT2.WARM.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL4.MPT2.WARM.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL4_MPT2_WARM_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL4.MPT2.WARM.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL4.MPT2.WARM.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL4_MPT2_COOL_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL4.MPT2.COOL.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL4.MPT2.COOL.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL4_MPT2_COOL_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL4.MPT2.COOL.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL4.MPT2.COOL.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL4_MPT2_COOL_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL4.MPT2.COOL.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL4.MPT2.COOL.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL4_MPT2_COOL_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL4.MPT2.COOL.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL4.MPT2.COOL.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL4_MPT2_COOL_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL4.MPT2.COOL.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL4.MPT2.COOL.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL4_MPT2_COOL_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL4.MPT2.COOL.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL4.MPT2.COOL.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL4_MPT2_COOL_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL4.MPT2.COOL.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL4.MPT2.COOL.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL4_MPT2_COOL_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL4.MPT2.COOL.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL4.MPT2.COOL.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL4_MPT2_COOL_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL4.MPT2.COOL.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL4.MPT2.COOL.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL4_MPT2_COMBINED_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL4.MPT2.COMBINED.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL4.MPT2.COMBINED.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL4_MPT2_COMBINED_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL4.MPT2.COMBINED.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL4.MPT2.COMBINED.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL4_MPT2_COMBINED_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL4.MPT2.COMBINED.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL4.MPT2.COMBINED.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL5_MPT1_WARM_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL5.MPT1.WARM.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL5.MPT1.WARM.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL5_MPT1_WARM_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL5.MPT1.WARM.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL5.MPT1.WARM.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL5_MPT1_WARM_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL5.MPT1.WARM.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL5.MPT1.WARM.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL5_MPT1_WARM_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL5.MPT1.WARM.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL5.MPT1.WARM.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL5_MPT1_WARM_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL5.MPT1.WARM.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL5.MPT1.WARM.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL5_MPT1_WARM_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL5.MPT1.WARM.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL5.MPT1.WARM.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL5_MPT1_WARM_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL5.MPT1.WARM.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL5.MPT1.WARM.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL5_MPT1_WARM_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL5.MPT1.WARM.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL5.MPT1.WARM.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL5_MPT1_WARM_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL5.MPT1.WARM.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL5.MPT1.WARM.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL5_MPT1_COOL_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL5.MPT1.COOL.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL5.MPT1.COOL.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL5_MPT1_COOL_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL5.MPT1.COOL.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL5.MPT1.COOL.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL5_MPT1_COOL_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL5.MPT1.COOL.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL5.MPT1.COOL.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL5_MPT1_COOL_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL5.MPT1.COOL.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL5.MPT1.COOL.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL5_MPT1_COOL_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL5.MPT1.COOL.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL5.MPT1.COOL.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL5_MPT1_COOL_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL5.MPT1.COOL.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL5.MPT1.COOL.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL5_MPT1_COOL_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL5.MPT1.COOL.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL5.MPT1.COOL.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL5_MPT1_COOL_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL5.MPT1.COOL.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL5.MPT1.COOL.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL5_MPT1_COOL_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL5.MPT1.COOL.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL5.MPT1.COOL.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL5_MPT1_COMBINED_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL5.MPT1.COMBINED.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL5.MPT1.COMBINED.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL5_MPT1_COMBINED_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL5.MPT1.COMBINED.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL5.MPT1.COMBINED.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL5_MPT1_COMBINED_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL5.MPT1.COMBINED.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL5.MPT1.COMBINED.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL5_MPT2_WARM_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL5.MPT2.WARM.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL5.MPT2.WARM.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL5_MPT2_WARM_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL5.MPT2.WARM.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL5.MPT2.WARM.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL5_MPT2_WARM_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL5.MPT2.WARM.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL5.MPT2.WARM.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL5_MPT2_WARM_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL5.MPT2.WARM.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL5.MPT2.WARM.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL5_MPT2_WARM_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL5.MPT2.WARM.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL5.MPT2.WARM.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL5_MPT2_WARM_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL5.MPT2.WARM.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL5.MPT2.WARM.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL5_MPT2_WARM_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL5.MPT2.WARM.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL5.MPT2.WARM.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL5_MPT2_WARM_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL5.MPT2.WARM.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL5.MPT2.WARM.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL5_MPT2_WARM_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL5.MPT2.WARM.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL5.MPT2.WARM.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL5_MPT2_COOL_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL5.MPT2.COOL.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL5.MPT2.COOL.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL5_MPT2_COOL_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL5.MPT2.COOL.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL5.MPT2.COOL.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL5_MPT2_COOL_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL5.MPT2.COOL.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL5.MPT2.COOL.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL5_MPT2_COOL_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL5.MPT2.COOL.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL5.MPT2.COOL.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL5_MPT2_COOL_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL5.MPT2.COOL.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL5.MPT2.COOL.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL5_MPT2_COOL_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL5.MPT2.COOL.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL5.MPT2.COOL.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL5_MPT2_COOL_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL5.MPT2.COOL.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL5.MPT2.COOL.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL5_MPT2_COOL_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL5.MPT2.COOL.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL5.MPT2.COOL.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL5_MPT2_COOL_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL5.MPT2.COOL.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL5.MPT2.COOL.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL5_MPT2_COMBINED_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL5.MPT2.COMBINED.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL5.MPT2.COMBINED.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL5_MPT2_COMBINED_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL5.MPT2.COMBINED.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL5.MPT2.COMBINED.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL5_MPT2_COMBINED_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL5.MPT2.COMBINED.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL5.MPT2.COMBINED.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL6_MPT1_WARM_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL6.MPT1.WARM.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL6.MPT1.WARM.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL6_MPT1_WARM_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL6.MPT1.WARM.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL6.MPT1.WARM.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL6_MPT1_WARM_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL6.MPT1.WARM.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL6.MPT1.WARM.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL6_MPT1_WARM_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL6.MPT1.WARM.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL6.MPT1.WARM.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL6_MPT1_WARM_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL6.MPT1.WARM.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL6.MPT1.WARM.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL6_MPT1_WARM_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL6.MPT1.WARM.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL6.MPT1.WARM.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL6_MPT1_WARM_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL6.MPT1.WARM.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL6.MPT1.WARM.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL6_MPT1_WARM_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL6.MPT1.WARM.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL6.MPT1.WARM.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL6_MPT1_WARM_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL6.MPT1.WARM.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL6.MPT1.WARM.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL6_MPT1_COOL_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL6.MPT1.COOL.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL6.MPT1.COOL.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL6_MPT1_COOL_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL6.MPT1.COOL.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL6.MPT1.COOL.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL6_MPT1_COOL_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL6.MPT1.COOL.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL6.MPT1.COOL.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL6_MPT1_COOL_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL6.MPT1.COOL.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL6.MPT1.COOL.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL6_MPT1_COOL_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL6.MPT1.COOL.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL6.MPT1.COOL.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL6_MPT1_COOL_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL6.MPT1.COOL.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL6.MPT1.COOL.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL6_MPT1_COOL_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL6.MPT1.COOL.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL6.MPT1.COOL.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL6_MPT1_COOL_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL6.MPT1.COOL.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL6.MPT1.COOL.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL6_MPT1_COOL_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL6.MPT1.COOL.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL6.MPT1.COOL.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL6_MPT1_COMBINED_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL6.MPT1.COMBINED.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL6.MPT1.COMBINED.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL6_MPT1_COMBINED_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL6.MPT1.COMBINED.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL6.MPT1.COMBINED.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL6_MPT1_COMBINED_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL6.MPT1.COMBINED.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL6.MPT1.COMBINED.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL6_MPT2_WARM_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL6.MPT2.WARM.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL6.MPT2.WARM.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL6_MPT2_WARM_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL6.MPT2.WARM.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL6.MPT2.WARM.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL6_MPT2_WARM_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL6.MPT2.WARM.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL6.MPT2.WARM.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL6_MPT2_WARM_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL6.MPT2.WARM.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL6.MPT2.WARM.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL6_MPT2_WARM_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL6.MPT2.WARM.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL6.MPT2.WARM.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL6_MPT2_WARM_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL6.MPT2.WARM.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL6.MPT2.WARM.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL6_MPT2_WARM_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL6.MPT2.WARM.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL6.MPT2.WARM.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL6_MPT2_WARM_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL6.MPT2.WARM.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL6.MPT2.WARM.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL6_MPT2_WARM_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL6.MPT2.WARM.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL6.MPT2.WARM.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL6_MPT2_COOL_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL6.MPT2.COOL.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL6.MPT2.COOL.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL6_MPT2_COOL_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL6.MPT2.COOL.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL6.MPT2.COOL.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL6_MPT2_COOL_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL6.MPT2.COOL.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL6.MPT2.COOL.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL6_MPT2_COOL_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL6.MPT2.COOL.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL6.MPT2.COOL.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL6_MPT2_COOL_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL6.MPT2.COOL.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL6.MPT2.COOL.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL6_MPT2_COOL_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL6.MPT2.COOL.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL6.MPT2.COOL.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL6_MPT2_COOL_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL6.MPT2.COOL.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL6.MPT2.COOL.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL6_MPT2_COOL_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL6.MPT2.COOL.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL6.MPT2.COOL.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL6_MPT2_COOL_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL6.MPT2.COOL.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL6.MPT2.COOL.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL6_MPT2_COMBINED_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL6.MPT2.COMBINED.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL6.MPT2.COMBINED.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL6_MPT2_COMBINED_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL6.MPT2.COMBINED.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL6.MPT2.COMBINED.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL6_MPT2_COMBINED_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL6.MPT2.COMBINED.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL6.MPT2.COMBINED.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL7_MPT1_WARM_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL7.MPT1.WARM.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL7.MPT1.WARM.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL7_MPT1_WARM_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL7.MPT1.WARM.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL7.MPT1.WARM.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL7_MPT1_WARM_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL7.MPT1.WARM.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL7.MPT1.WARM.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL7_MPT1_WARM_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL7.MPT1.WARM.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL7.MPT1.WARM.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL7_MPT1_WARM_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL7.MPT1.WARM.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL7.MPT1.WARM.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL7_MPT1_WARM_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL7.MPT1.WARM.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL7.MPT1.WARM.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL7_MPT1_WARM_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL7.MPT1.WARM.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL7.MPT1.WARM.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL7_MPT1_WARM_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL7.MPT1.WARM.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL7.MPT1.WARM.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL7_MPT1_WARM_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL7.MPT1.WARM.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL7.MPT1.WARM.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL7_MPT1_COOL_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL7.MPT1.COOL.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL7.MPT1.COOL.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL7_MPT1_COOL_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL7.MPT1.COOL.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL7.MPT1.COOL.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL7_MPT1_COOL_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL7.MPT1.COOL.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL7.MPT1.COOL.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL7_MPT1_COOL_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL7.MPT1.COOL.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL7.MPT1.COOL.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL7_MPT1_COOL_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL7.MPT1.COOL.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL7.MPT1.COOL.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL7_MPT1_COOL_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL7.MPT1.COOL.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL7.MPT1.COOL.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL7_MPT1_COOL_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL7.MPT1.COOL.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL7.MPT1.COOL.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL7_MPT1_COOL_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL7.MPT1.COOL.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL7.MPT1.COOL.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL7_MPT1_COOL_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL7.MPT1.COOL.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL7.MPT1.COOL.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL7_MPT1_COMBINED_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL7.MPT1.COMBINED.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL7.MPT1.COMBINED.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL7_MPT1_COMBINED_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL7.MPT1.COMBINED.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL7.MPT1.COMBINED.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL7_MPT1_COMBINED_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL7.MPT1.COMBINED.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL7.MPT1.COMBINED.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL7_MPT2_WARM_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL7.MPT2.WARM.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL7.MPT2.WARM.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL7_MPT2_WARM_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL7.MPT2.WARM.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL7.MPT2.WARM.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL7_MPT2_WARM_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL7.MPT2.WARM.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL7.MPT2.WARM.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL7_MPT2_WARM_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL7.MPT2.WARM.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL7.MPT2.WARM.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL7_MPT2_WARM_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL7.MPT2.WARM.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL7.MPT2.WARM.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL7_MPT2_WARM_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL7.MPT2.WARM.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL7.MPT2.WARM.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL7_MPT2_WARM_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL7.MPT2.WARM.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL7.MPT2.WARM.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL7_MPT2_WARM_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL7.MPT2.WARM.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL7.MPT2.WARM.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL7_MPT2_WARM_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL7.MPT2.WARM.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL7.MPT2.WARM.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL7_MPT2_COOL_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL7.MPT2.COOL.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL7.MPT2.COOL.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL7_MPT2_COOL_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL7.MPT2.COOL.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL7.MPT2.COOL.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL7_MPT2_COOL_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL7.MPT2.COOL.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL7.MPT2.COOL.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL7_MPT2_COOL_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL7.MPT2.COOL.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL7.MPT2.COOL.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL7_MPT2_COOL_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL7.MPT2.COOL.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL7.MPT2.COOL.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL7_MPT2_COOL_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL7.MPT2.COOL.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL7.MPT2.COOL.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL7_MPT2_COOL_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL7.MPT2.COOL.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL7.MPT2.COOL.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL7_MPT2_COOL_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL7.MPT2.COOL.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL7.MPT2.COOL.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL7_MPT2_COOL_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL7.MPT2.COOL.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL7.MPT2.COOL.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL7_MPT2_COMBINED_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL7.MPT2.COMBINED.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL7.MPT2.COMBINED.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL7_MPT2_COMBINED_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL7.MPT2.COMBINED.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL7.MPT2.COMBINED.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL7_MPT2_COMBINED_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL7.MPT2.COMBINED.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL7.MPT2.COMBINED.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL8_MPT1_WARM_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL8.MPT1.WARM.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL8.MPT1.WARM.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL8_MPT1_WARM_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL8.MPT1.WARM.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL8.MPT1.WARM.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL8_MPT1_WARM_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL8.MPT1.WARM.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL8.MPT1.WARM.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL8_MPT1_WARM_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL8.MPT1.WARM.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL8.MPT1.WARM.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL8_MPT1_WARM_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL8.MPT1.WARM.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL8.MPT1.WARM.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL8_MPT1_WARM_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL8.MPT1.WARM.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL8.MPT1.WARM.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL8_MPT1_WARM_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL8.MPT1.WARM.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL8.MPT1.WARM.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL8_MPT1_WARM_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL8.MPT1.WARM.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL8.MPT1.WARM.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL8_MPT1_WARM_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL8.MPT1.WARM.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL8.MPT1.WARM.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL8_MPT1_COOL_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL8.MPT1.COOL.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL8.MPT1.COOL.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL8_MPT1_COOL_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL8.MPT1.COOL.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL8.MPT1.COOL.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL8_MPT1_COOL_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL8.MPT1.COOL.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL8.MPT1.COOL.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL8_MPT1_COOL_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL8.MPT1.COOL.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL8.MPT1.COOL.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL8_MPT1_COOL_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL8.MPT1.COOL.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL8.MPT1.COOL.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL8_MPT1_COOL_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL8.MPT1.COOL.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL8.MPT1.COOL.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL8_MPT1_COOL_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL8.MPT1.COOL.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL8.MPT1.COOL.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL8_MPT1_COOL_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL8.MPT1.COOL.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL8.MPT1.COOL.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL8_MPT1_COOL_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL8.MPT1.COOL.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL8.MPT1.COOL.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL8_MPT1_COMBINED_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL8.MPT1.COMBINED.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL8.MPT1.COMBINED.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL8_MPT1_COMBINED_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL8.MPT1.COMBINED.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL8.MPT1.COMBINED.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL8_MPT1_COMBINED_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL8.MPT1.COMBINED.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL8.MPT1.COMBINED.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL8_MPT2_WARM_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL8.MPT2.WARM.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL8.MPT2.WARM.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL8_MPT2_WARM_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL8.MPT2.WARM.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL8.MPT2.WARM.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL8_MPT2_WARM_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL8.MPT2.WARM.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL8.MPT2.WARM.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL8_MPT2_WARM_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL8.MPT2.WARM.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL8.MPT2.WARM.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL8_MPT2_WARM_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL8.MPT2.WARM.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL8.MPT2.WARM.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL8_MPT2_WARM_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL8.MPT2.WARM.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL8.MPT2.WARM.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL8_MPT2_WARM_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL8.MPT2.WARM.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL8.MPT2.WARM.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL8_MPT2_WARM_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL8.MPT2.WARM.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL8.MPT2.WARM.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL8_MPT2_WARM_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL8.MPT2.WARM.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL8.MPT2.WARM.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL8_MPT2_COOL_SENSOR0_16 = new string[] { "SG.CR11.DLECT.PANEL8.MPT2.COOL.SENSOR0_DMX_16.LUX", "SG.CR11.DLECT.PANEL8.MPT2.COOL.SENSOR0_DMX_16.CCT" };
        private static string[] PANEL8_MPT2_COOL_SENSOR1_16 = new string[] { "SG.CR11.DLECT.PANEL8.MPT2.COOL.SENSOR1_DMX_16.LUX", "SG.CR11.DLECT.PANEL8.MPT2.COOL.SENSOR1_DMX_16.CCT" };
        private static string[] PANEL8_MPT2_COOL_SENSOR2_16 = new string[] { "SG.CR11.DLECT.PANEL8.MPT2.COOL.SENSOR2_DMX_16.LUX", "SG.CR11.DLECT.PANEL8.MPT2.COOL.SENSOR2_DMX_16.CCT" };
        private static string[] PANEL8_MPT2_COOL_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL8.MPT2.COOL.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL8.MPT2.COOL.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL8_MPT2_COOL_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL8.MPT2.COOL.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL8.MPT2.COOL.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL8_MPT2_COOL_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL8.MPT2.COOL.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL8.MPT2.COOL.SENSOR2_DMX_64.CCT" };
        private static string[] PANEL8_MPT2_COOL_SENSOR0_128 = new string[] { "SG.CR11.DLECT.PANEL8.MPT2.COOL.SENSOR0_DMX_128.LUX", "SG.CR11.DLECT.PANEL8.MPT2.COOL.SENSOR0_DMX_128.CCT" };
        private static string[] PANEL8_MPT2_COOL_SENSOR1_128 = new string[] { "SG.CR11.DLECT.PANEL8.MPT2.COOL.SENSOR1_DMX_128.LUX", "SG.CR11.DLECT.PANEL8.MPT2.COOL.SENSOR1_DMX_128.CCT" };
        private static string[] PANEL8_MPT2_COOL_SENSOR2_128 = new string[] { "SG.CR11.DLECT.PANEL8.MPT2.COOL.SENSOR2_DMX_128.LUX", "SG.CR11.DLECT.PANEL8.MPT2.COOL.SENSOR2_DMX_128.CCT" };
        private static string[] PANEL8_MPT2_COMBINED_SENSOR0_64 = new string[] { "SG.CR11.DLECT.PANEL8.MPT2.COMBINED.SENSOR0_DMX_64.LUX", "SG.CR11.DLECT.PANEL8.MPT2.COMBINED.SENSOR0_DMX_64.CCT" };
        private static string[] PANEL8_MPT2_COMBINED_SENSOR1_64 = new string[] { "SG.CR11.DLECT.PANEL8.MPT2.COMBINED.SENSOR1_DMX_64.LUX", "SG.CR11.DLECT.PANEL8.MPT2.COMBINED.SENSOR1_DMX_64.CCT" };
        private static string[] PANEL8_MPT2_COMBINED_SENSOR2_64 = new string[] { "SG.CR11.DLECT.PANEL8.MPT2.COMBINED.SENSOR2_DMX_64.LUX", "SG.CR11.DLECT.PANEL8.MPT2.COMBINED.SENSOR2_DMX_64.CCT" };
        #endregion


        /// <summary>
        /// Method to add Panel 1 Measurement location Left Point tags to a List
        /// </summary>
        /// <returns></returns>
        public static string[] Panel1Left()
        {
            panel1Left.Clear();
            panel1Left.AddRange(PANEL1_MPT1_WARM_SENSOR0_16);
            panel1Left.AddRange(PANEL1_MPT1_WARM_SENSOR1_16);
            panel1Left.AddRange(PANEL1_MPT1_WARM_SENSOR2_16);
            panel1Left.AddRange(PANEL1_MPT1_WARM_SENSOR0_64);
            panel1Left.AddRange(PANEL1_MPT1_WARM_SENSOR1_64);
            panel1Left.AddRange(PANEL1_MPT1_WARM_SENSOR2_64);
            panel1Left.AddRange(PANEL1_MPT1_WARM_SENSOR0_128);
            panel1Left.AddRange(PANEL1_MPT1_WARM_SENSOR1_128);
            panel1Left.AddRange(PANEL1_MPT1_WARM_SENSOR2_128);
            panel1Left.AddRange(PANEL1_MPT1_COOL_SENSOR0_16);
            panel1Left.AddRange(PANEL1_MPT1_COOL_SENSOR1_16);
            panel1Left.AddRange(PANEL1_MPT1_COOL_SENSOR2_16);
            panel1Left.AddRange(PANEL1_MPT1_COOL_SENSOR0_64);
            panel1Left.AddRange(PANEL1_MPT1_COOL_SENSOR1_64);
            panel1Left.AddRange(PANEL1_MPT1_COOL_SENSOR2_64);
            panel1Left.AddRange(PANEL1_MPT1_COOL_SENSOR0_128);
            panel1Left.AddRange(PANEL1_MPT1_COOL_SENSOR1_128);
            panel1Left.AddRange(PANEL1_MPT1_COOL_SENSOR2_128);
            panel1Left.AddRange(PANEL1_MPT1_COMBINED_SENSOR0_64);
            panel1Left.AddRange(PANEL1_MPT1_COMBINED_SENSOR1_64);
            panel1Left.AddRange(PANEL1_MPT1_COMBINED_SENSOR2_64);
            user_commentsTag = "SG.CR11.DLECT.PANEL1.MPT1.ANNOTATE_USER_COMMENT";
            stop_session_commentsTag = "SG.CR11.DLECT.PANEL1.MPT1.ANNOTATE_STOP_SESSION";
            return panel1Left.ToArray();
        }


        /// <summary>
        /// Method to add Panel 1 Measurement location Right Point tags to a List
        /// </summary>
        /// <returns></returns>
        public static string[] Panel1Right()
        {
            panel1Right.Clear();
            panel1Right.AddRange(PANEL1_MPT2_WARM_SENSOR0_16);
            panel1Right.AddRange(PANEL1_MPT2_WARM_SENSOR1_16);
            panel1Right.AddRange(PANEL1_MPT2_WARM_SENSOR2_16);
            panel1Right.AddRange(PANEL1_MPT2_WARM_SENSOR0_64);
            panel1Right.AddRange(PANEL1_MPT2_WARM_SENSOR1_64);
            panel1Right.AddRange(PANEL1_MPT2_WARM_SENSOR2_64);
            panel1Right.AddRange(PANEL1_MPT2_WARM_SENSOR0_128);
            panel1Right.AddRange(PANEL1_MPT2_WARM_SENSOR1_128);
            panel1Right.AddRange(PANEL1_MPT2_WARM_SENSOR2_128);
            panel1Right.AddRange(PANEL1_MPT2_COOL_SENSOR0_16);
            panel1Right.AddRange(PANEL1_MPT2_COOL_SENSOR1_16);
            panel1Right.AddRange(PANEL1_MPT2_COOL_SENSOR2_16);
            panel1Right.AddRange(PANEL1_MPT2_COOL_SENSOR0_64);
            panel1Right.AddRange(PANEL1_MPT2_COOL_SENSOR1_64);
            panel1Right.AddRange(PANEL1_MPT2_COOL_SENSOR2_64);
            panel1Right.AddRange(PANEL1_MPT2_COOL_SENSOR0_128);
            panel1Right.AddRange(PANEL1_MPT2_COOL_SENSOR1_128);
            panel1Right.AddRange(PANEL1_MPT2_COOL_SENSOR2_128);
            panel1Right.AddRange(PANEL1_MPT2_COMBINED_SENSOR0_64);
            panel1Right.AddRange(PANEL1_MPT2_COMBINED_SENSOR1_64);
            panel1Right.AddRange(PANEL1_MPT2_COMBINED_SENSOR2_64);
            user_commentsTag = "SG.CR11.DLECT.PANEL1.MPT2.ANNOTATE_USER_COMMENT";
            stop_session_commentsTag = "SG.CR11.DLECT.PANEL1.MPT2.ANNOTATE_STOP_SESSION";
            return panel1Right.ToArray();
        }

        /// <summary>
        /// Method to add Panel 2 Measurement location Left Point tags to a List
        /// </summary>
        /// <returns></returns>
        public static string[] Panel2Left()
        {
            panel2Left.Clear();
            panel2Left.AddRange(PANEL2_MPT1_WARM_SENSOR0_16);
            panel2Left.AddRange(PANEL2_MPT1_WARM_SENSOR1_16);
            panel2Left.AddRange(PANEL2_MPT1_WARM_SENSOR2_16);
            panel2Left.AddRange(PANEL2_MPT1_WARM_SENSOR0_64);
            panel2Left.AddRange(PANEL2_MPT1_WARM_SENSOR1_64);
            panel2Left.AddRange(PANEL2_MPT1_WARM_SENSOR2_64);
            panel2Left.AddRange(PANEL2_MPT1_WARM_SENSOR0_128);
            panel2Left.AddRange(PANEL2_MPT1_WARM_SENSOR1_128);
            panel2Left.AddRange(PANEL2_MPT1_WARM_SENSOR2_128);
            panel2Left.AddRange(PANEL2_MPT1_COOL_SENSOR0_16);
            panel2Left.AddRange(PANEL2_MPT1_COOL_SENSOR1_16);
            panel2Left.AddRange(PANEL2_MPT1_COOL_SENSOR2_16);
            panel2Left.AddRange(PANEL2_MPT1_COOL_SENSOR0_64);
            panel2Left.AddRange(PANEL2_MPT1_COOL_SENSOR1_64);
            panel2Left.AddRange(PANEL2_MPT1_COOL_SENSOR2_64);
            panel2Left.AddRange(PANEL2_MPT1_COOL_SENSOR0_128);
            panel2Left.AddRange(PANEL2_MPT1_COOL_SENSOR1_128);
            panel2Left.AddRange(PANEL2_MPT1_COOL_SENSOR2_128);
            panel2Left.AddRange(PANEL2_MPT1_COMBINED_SENSOR0_64);
            panel2Left.AddRange(PANEL2_MPT1_COMBINED_SENSOR1_64);
            panel2Left.AddRange(PANEL2_MPT1_COMBINED_SENSOR2_64);
            user_commentsTag = "SG.CR11.DLECT.PANEL2.MPT1.ANNOTATE_USER_COMMENT";
            stop_session_commentsTag = "SG.CR11.DLECT.PANEL2.MPT1.ANNOTATE_STOP_SESSION";
            return panel2Left.ToArray();
        }

        /// <summary>
        /// Method to add Panel 2 Measurement location Right Point tags to a List
        /// </summary>
        /// <returns></returns>
        public static string[] Panel2Right()
        {
            panel2Right.Clear();
            panel2Right.AddRange(PANEL2_MPT2_WARM_SENSOR0_16);
            panel2Right.AddRange(PANEL2_MPT2_WARM_SENSOR1_16);
            panel2Right.AddRange(PANEL2_MPT2_WARM_SENSOR2_16);
            panel2Right.AddRange(PANEL2_MPT2_WARM_SENSOR0_64);
            panel2Right.AddRange(PANEL2_MPT2_WARM_SENSOR1_64);
            panel2Right.AddRange(PANEL2_MPT2_WARM_SENSOR2_64);
            panel2Right.AddRange(PANEL2_MPT2_WARM_SENSOR0_128);
            panel2Right.AddRange(PANEL2_MPT2_WARM_SENSOR1_128);
            panel2Right.AddRange(PANEL2_MPT2_WARM_SENSOR2_128);
            panel2Right.AddRange(PANEL2_MPT2_COOL_SENSOR0_16);
            panel2Right.AddRange(PANEL2_MPT2_COOL_SENSOR1_16);
            panel2Right.AddRange(PANEL2_MPT2_COOL_SENSOR2_16);
            panel2Right.AddRange(PANEL2_MPT2_COOL_SENSOR0_64);
            panel2Right.AddRange(PANEL2_MPT2_COOL_SENSOR1_64);
            panel2Right.AddRange(PANEL2_MPT2_COOL_SENSOR2_64);
            panel2Right.AddRange(PANEL2_MPT2_COOL_SENSOR0_128);
            panel2Right.AddRange(PANEL2_MPT2_COOL_SENSOR1_128);
            panel2Right.AddRange(PANEL2_MPT2_COOL_SENSOR2_128);
            panel2Right.AddRange(PANEL2_MPT2_COMBINED_SENSOR0_64);
            panel2Right.AddRange(PANEL2_MPT2_COMBINED_SENSOR1_64);
            panel2Right.AddRange(PANEL2_MPT2_COMBINED_SENSOR2_64);
            user_commentsTag = "SG.CR11.DLECT.PANEL2.MPT2.ANNOTATE_USER_COMMENT";
            stop_session_commentsTag = "SG.CR11.DLECT.PANEL2.MPT2.ANNOTATE_STOP_SESSION";
            return panel2Right.ToArray();
        }

        /// <summary>
        /// Method to add Panel 3 Measurement location Left Point tags to a List
        /// </summary>
        /// <returns></returns>
        public static string[] Panel3Left()
        {
            panel3Left.Clear();
            panel3Left.AddRange(PANEL3_MPT1_WARM_SENSOR0_16);
            panel3Left.AddRange(PANEL3_MPT1_WARM_SENSOR1_16);
            panel3Left.AddRange(PANEL3_MPT1_WARM_SENSOR2_16);
            panel3Left.AddRange(PANEL3_MPT1_WARM_SENSOR0_64);
            panel3Left.AddRange(PANEL3_MPT1_WARM_SENSOR1_64);
            panel3Left.AddRange(PANEL3_MPT1_WARM_SENSOR2_64);
            panel3Left.AddRange(PANEL3_MPT1_WARM_SENSOR0_128);
            panel3Left.AddRange(PANEL3_MPT1_WARM_SENSOR1_128);
            panel3Left.AddRange(PANEL3_MPT1_WARM_SENSOR2_128);
            panel3Left.AddRange(PANEL3_MPT1_COOL_SENSOR0_16);
            panel3Left.AddRange(PANEL3_MPT1_COOL_SENSOR1_16);
            panel3Left.AddRange(PANEL3_MPT1_COOL_SENSOR2_16);
            panel3Left.AddRange(PANEL3_MPT1_COOL_SENSOR0_64);
            panel3Left.AddRange(PANEL3_MPT1_COOL_SENSOR1_64);
            panel3Left.AddRange(PANEL3_MPT1_COOL_SENSOR2_64);
            panel3Left.AddRange(PANEL3_MPT1_COOL_SENSOR0_128);
            panel3Left.AddRange(PANEL3_MPT1_COOL_SENSOR1_128);
            panel3Left.AddRange(PANEL3_MPT1_COOL_SENSOR2_128);
            panel3Left.AddRange(PANEL3_MPT1_COMBINED_SENSOR0_64);
            panel3Left.AddRange(PANEL3_MPT1_COMBINED_SENSOR1_64);
            panel3Left.AddRange(PANEL3_MPT1_COMBINED_SENSOR2_64);
            user_commentsTag = "SG.CR11.DLECT.PANEL3.MPT1.ANNOTATE_USER_COMMENT";
            stop_session_commentsTag = "SG.CR11.DLECT.PANEL3.MPT1.ANNOTATE_STOP_SESSION";
            return panel3Left.ToArray();
        }

        /// <summary>
        /// Method to add Panel 3 Measurement location Right Point tags to a List
        /// </summary>
        /// <returns></returns>
        public static string[] Panel3Right()
        {
            panel3Right.Clear();
            panel3Right.AddRange(PANEL3_MPT2_WARM_SENSOR0_16);
            panel3Right.AddRange(PANEL3_MPT2_WARM_SENSOR1_16);
            panel3Right.AddRange(PANEL3_MPT2_WARM_SENSOR2_16);
            panel3Right.AddRange(PANEL3_MPT2_WARM_SENSOR0_64);
            panel3Right.AddRange(PANEL3_MPT2_WARM_SENSOR1_64);
            panel3Right.AddRange(PANEL3_MPT2_WARM_SENSOR2_64);
            panel3Right.AddRange(PANEL3_MPT2_WARM_SENSOR0_128);
            panel3Right.AddRange(PANEL3_MPT2_WARM_SENSOR1_128);
            panel3Right.AddRange(PANEL3_MPT2_WARM_SENSOR2_128);
            panel3Right.AddRange(PANEL3_MPT2_COOL_SENSOR0_16);
            panel3Right.AddRange(PANEL3_MPT2_COOL_SENSOR1_16);
            panel3Right.AddRange(PANEL3_MPT2_COOL_SENSOR2_16);
            panel3Right.AddRange(PANEL3_MPT2_COOL_SENSOR0_64);
            panel3Right.AddRange(PANEL3_MPT2_COOL_SENSOR1_64);
            panel3Right.AddRange(PANEL3_MPT2_COOL_SENSOR2_64);
            panel3Right.AddRange(PANEL3_MPT2_COOL_SENSOR0_128);
            panel3Right.AddRange(PANEL3_MPT2_COOL_SENSOR1_128);
            panel3Right.AddRange(PANEL3_MPT2_COOL_SENSOR2_128);
            panel3Right.AddRange(PANEL3_MPT2_COMBINED_SENSOR0_64);
            panel3Right.AddRange(PANEL3_MPT2_COMBINED_SENSOR1_64);
            panel3Right.AddRange(PANEL3_MPT2_COMBINED_SENSOR2_64);
            user_commentsTag = "SG.CR11.DLECT.PANEL3.MPT2.ANNOTATE_USER_COMMENT";
            stop_session_commentsTag = "SG.CR11.DLECT.PANEL3.MPT2.ANNOTATE_STOP_SESSION";
            return panel3Right.ToArray();
        }

        /// <summary>
        /// Method to add Panel 4 Measurement location Left Point tags to a List
        /// </summary>
        /// <returns></returns>
        public static string[] Panel4Left()
        {
            panel4Left.Clear();
            panel4Left.AddRange(PANEL4_MPT1_WARM_SENSOR0_16);
            panel4Left.AddRange(PANEL4_MPT1_WARM_SENSOR1_16);
            panel4Left.AddRange(PANEL4_MPT1_WARM_SENSOR2_16);
            panel4Left.AddRange(PANEL4_MPT1_WARM_SENSOR0_64);
            panel4Left.AddRange(PANEL4_MPT1_WARM_SENSOR1_64);
            panel4Left.AddRange(PANEL4_MPT1_WARM_SENSOR2_64);
            panel4Left.AddRange(PANEL4_MPT1_WARM_SENSOR0_128);
            panel4Left.AddRange(PANEL4_MPT1_WARM_SENSOR1_128);
            panel4Left.AddRange(PANEL4_MPT1_WARM_SENSOR2_128);
            panel4Left.AddRange(PANEL4_MPT1_COOL_SENSOR0_16);
            panel4Left.AddRange(PANEL4_MPT1_COOL_SENSOR1_16);
            panel4Left.AddRange(PANEL4_MPT1_COOL_SENSOR2_16);
            panel4Left.AddRange(PANEL4_MPT1_COOL_SENSOR0_64);
            panel4Left.AddRange(PANEL4_MPT1_COOL_SENSOR1_64);
            panel4Left.AddRange(PANEL4_MPT1_COOL_SENSOR2_64);
            panel4Left.AddRange(PANEL4_MPT1_COOL_SENSOR0_128);
            panel4Left.AddRange(PANEL4_MPT1_COOL_SENSOR1_128);
            panel4Left.AddRange(PANEL4_MPT1_COOL_SENSOR2_128);
            panel4Left.AddRange(PANEL4_MPT1_COMBINED_SENSOR0_64);
            panel4Left.AddRange(PANEL4_MPT1_COMBINED_SENSOR1_64);
            panel4Left.AddRange(PANEL4_MPT1_COMBINED_SENSOR2_64);
            user_commentsTag = "SG.CR11.DLECT.PANEL4.MPT1.ANNOTATE_USER_COMMENT";
            stop_session_commentsTag = "SG.CR11.DLECT.PANEL4.MPT1.ANNOTATE_STOP_SESSION";
            return panel4Left.ToArray();
        }

        /// <summary>
        /// Method to add Panel 4 Measurement location Right Point tags to a List
        /// </summary>
        /// <returns></returns>
        public static string[] Panel4Right()
        {
            panel4Right.Clear();
            panel4Right.AddRange(PANEL4_MPT2_WARM_SENSOR0_16);
            panel4Right.AddRange(PANEL4_MPT2_WARM_SENSOR1_16);
            panel4Right.AddRange(PANEL4_MPT2_WARM_SENSOR2_16);
            panel4Right.AddRange(PANEL4_MPT2_WARM_SENSOR0_64);
            panel4Right.AddRange(PANEL4_MPT2_WARM_SENSOR1_64);
            panel4Right.AddRange(PANEL4_MPT2_WARM_SENSOR2_64);
            panel4Right.AddRange(PANEL4_MPT2_WARM_SENSOR0_128);
            panel4Right.AddRange(PANEL4_MPT2_WARM_SENSOR1_128);
            panel4Right.AddRange(PANEL4_MPT2_WARM_SENSOR2_128);
            panel4Right.AddRange(PANEL4_MPT2_COOL_SENSOR0_16);
            panel4Right.AddRange(PANEL4_MPT2_COOL_SENSOR1_16);
            panel4Right.AddRange(PANEL4_MPT2_COOL_SENSOR2_16);
            panel4Right.AddRange(PANEL4_MPT2_COOL_SENSOR0_64);
            panel4Right.AddRange(PANEL4_MPT2_COOL_SENSOR1_64);
            panel4Right.AddRange(PANEL4_MPT2_COOL_SENSOR2_64);
            panel4Right.AddRange(PANEL4_MPT2_COOL_SENSOR0_128);
            panel4Right.AddRange(PANEL4_MPT2_COOL_SENSOR1_128);
            panel4Right.AddRange(PANEL4_MPT2_COOL_SENSOR2_128);
            panel4Right.AddRange(PANEL4_MPT2_COMBINED_SENSOR0_64);
            panel4Right.AddRange(PANEL4_MPT2_COMBINED_SENSOR1_64);
            panel4Right.AddRange(PANEL4_MPT2_COMBINED_SENSOR2_64);
            user_commentsTag = "SG.CR11.DLECT.PANEL4.MPT2.ANNOTATE_USER_COMMENT";
            stop_session_commentsTag = "SG.CR11.DLECT.PANEL4.MPT2.ANNOTATE_STOP_SESSION";
            return panel4Right.ToArray();
        }


        /// <summary>
        /// Method to add Panel 5 Measurement location Left Point tags to a List
        /// </summary>
        /// <returns></returns>
        public static string[] Panel5Left()
        {
            panel5Left.Clear();
            panel5Left.AddRange(PANEL5_MPT1_WARM_SENSOR0_16);
            panel5Left.AddRange(PANEL5_MPT1_WARM_SENSOR1_16);
            panel5Left.AddRange(PANEL5_MPT1_WARM_SENSOR2_16);
            panel5Left.AddRange(PANEL5_MPT1_WARM_SENSOR0_64);
            panel5Left.AddRange(PANEL5_MPT1_WARM_SENSOR1_64);
            panel5Left.AddRange(PANEL5_MPT1_WARM_SENSOR2_64);
            panel5Left.AddRange(PANEL5_MPT1_WARM_SENSOR0_128);
            panel5Left.AddRange(PANEL5_MPT1_WARM_SENSOR1_128);
            panel5Left.AddRange(PANEL5_MPT1_WARM_SENSOR2_128);
            panel5Left.AddRange(PANEL5_MPT1_COOL_SENSOR0_16);
            panel5Left.AddRange(PANEL5_MPT1_COOL_SENSOR1_16);
            panel5Left.AddRange(PANEL5_MPT1_COOL_SENSOR2_16);
            panel5Left.AddRange(PANEL5_MPT1_COOL_SENSOR0_64);
            panel5Left.AddRange(PANEL5_MPT1_COOL_SENSOR1_64);
            panel5Left.AddRange(PANEL5_MPT1_COOL_SENSOR2_64);
            panel5Left.AddRange(PANEL5_MPT1_COOL_SENSOR0_128);
            panel5Left.AddRange(PANEL5_MPT1_COOL_SENSOR1_128);
            panel5Left.AddRange(PANEL5_MPT1_COOL_SENSOR2_128);
            panel5Left.AddRange(PANEL5_MPT1_COMBINED_SENSOR0_64);
            panel5Left.AddRange(PANEL5_MPT1_COMBINED_SENSOR1_64);
            panel5Left.AddRange(PANEL5_MPT1_COMBINED_SENSOR2_64);
            user_commentsTag = "SG.CR11.DLECT.PANEL5.MPT1.ANNOTATE_USER_COMMENT";
            stop_session_commentsTag = "SG.CR11.DLECT.PANEL5.MPT1.ANNOTATE_STOP_SESSION";
            return panel5Left.ToArray();
        }


        /// <summary>
        /// Method to add Panel 5 Measurement location Right Point tags to a List
        /// </summary>
        /// <returns></returns>
        public static string[] Panel5Right()
        {
            panel5Right.Clear();
            panel5Right.AddRange(PANEL5_MPT2_WARM_SENSOR0_16);
            panel5Right.AddRange(PANEL5_MPT2_WARM_SENSOR1_16);
            panel5Right.AddRange(PANEL5_MPT2_WARM_SENSOR2_16);
            panel5Right.AddRange(PANEL5_MPT2_WARM_SENSOR0_64);
            panel5Right.AddRange(PANEL5_MPT2_WARM_SENSOR1_64);
            panel5Right.AddRange(PANEL5_MPT2_WARM_SENSOR2_64);
            panel5Right.AddRange(PANEL5_MPT2_WARM_SENSOR0_128);
            panel5Right.AddRange(PANEL5_MPT2_WARM_SENSOR1_128);
            panel5Right.AddRange(PANEL5_MPT2_WARM_SENSOR2_128);
            panel5Right.AddRange(PANEL5_MPT2_COOL_SENSOR0_16);
            panel5Right.AddRange(PANEL5_MPT2_COOL_SENSOR1_16);
            panel5Right.AddRange(PANEL5_MPT2_COOL_SENSOR2_16);
            panel5Right.AddRange(PANEL5_MPT2_COOL_SENSOR0_64);
            panel5Right.AddRange(PANEL5_MPT2_COOL_SENSOR1_64);
            panel5Right.AddRange(PANEL5_MPT2_COOL_SENSOR2_64);
            panel5Right.AddRange(PANEL5_MPT2_COOL_SENSOR0_128);
            panel5Right.AddRange(PANEL5_MPT2_COOL_SENSOR1_128);
            panel5Right.AddRange(PANEL5_MPT2_COOL_SENSOR2_128);
            panel5Right.AddRange(PANEL5_MPT2_COMBINED_SENSOR0_64);
            panel5Right.AddRange(PANEL5_MPT2_COMBINED_SENSOR1_64);
            panel5Right.AddRange(PANEL5_MPT2_COMBINED_SENSOR2_64);
            user_commentsTag = "SG.CR11.DLECT.PANEL5.MPT2.ANNOTATE_USER_COMMENT";
            stop_session_commentsTag = "SG.CR11.DLECT.PANEL5.MPT2.ANNOTATE_STOP_SESSION";
            return panel5Right.ToArray();
        }


        /// <summary>
        /// Method to add Panel 6 Measurement location Left Point tags to a List
        /// </summary>
        /// <returns></returns>
        public static string[] Panel6Left()
        {
            panel6Left.Clear();
            panel6Left.AddRange(PANEL6_MPT1_WARM_SENSOR0_16);
            panel6Left.AddRange(PANEL6_MPT1_WARM_SENSOR1_16);
            panel6Left.AddRange(PANEL6_MPT1_WARM_SENSOR2_16);
            panel6Left.AddRange(PANEL6_MPT1_WARM_SENSOR0_64);
            panel6Left.AddRange(PANEL6_MPT1_WARM_SENSOR1_64);
            panel6Left.AddRange(PANEL6_MPT1_WARM_SENSOR2_64);
            panel6Left.AddRange(PANEL6_MPT1_WARM_SENSOR0_128);
            panel6Left.AddRange(PANEL6_MPT1_WARM_SENSOR1_128);
            panel6Left.AddRange(PANEL6_MPT1_WARM_SENSOR2_128);
            panel6Left.AddRange(PANEL6_MPT1_COOL_SENSOR0_16);
            panel6Left.AddRange(PANEL6_MPT1_COOL_SENSOR1_16);
            panel6Left.AddRange(PANEL6_MPT1_COOL_SENSOR2_16);
            panel6Left.AddRange(PANEL6_MPT1_COOL_SENSOR0_64);
            panel6Left.AddRange(PANEL6_MPT1_COOL_SENSOR1_64);
            panel6Left.AddRange(PANEL6_MPT1_COOL_SENSOR2_64);
            panel6Left.AddRange(PANEL6_MPT1_COOL_SENSOR0_128);
            panel6Left.AddRange(PANEL6_MPT1_COOL_SENSOR1_128);
            panel6Left.AddRange(PANEL6_MPT1_COOL_SENSOR2_128);
            panel6Left.AddRange(PANEL6_MPT1_COMBINED_SENSOR0_64);
            panel6Left.AddRange(PANEL6_MPT1_COMBINED_SENSOR1_64);
            panel6Left.AddRange(PANEL6_MPT1_COMBINED_SENSOR2_64);
            user_commentsTag = "SG.CR11.DLECT.PANEL6.MPT1.ANNOTATE_USER_COMMENT";
            stop_session_commentsTag = "SG.CR11.DLECT.PANEL6.MPT1.ANNOTATE_STOP_SESSION";
            return panel6Left.ToArray();
        }

        /// <summary>
        /// Method to add Panel 6 Measurement location Right Point tags to a List
        /// </summary>
        /// <returns></returns>
        public static string[] Panel6Right()
        {
            panel6Right.Clear();
            panel6Right.AddRange(PANEL6_MPT2_WARM_SENSOR0_16);
            panel6Right.AddRange(PANEL6_MPT2_WARM_SENSOR1_16);
            panel6Right.AddRange(PANEL6_MPT2_WARM_SENSOR2_16);
            panel6Right.AddRange(PANEL6_MPT2_WARM_SENSOR0_64);
            panel6Right.AddRange(PANEL6_MPT2_WARM_SENSOR1_64);
            panel6Right.AddRange(PANEL6_MPT2_WARM_SENSOR2_64);
            panel6Right.AddRange(PANEL6_MPT2_WARM_SENSOR0_128);
            panel6Right.AddRange(PANEL6_MPT2_WARM_SENSOR1_128);
            panel6Right.AddRange(PANEL6_MPT2_WARM_SENSOR2_128);
            panel6Right.AddRange(PANEL6_MPT2_COOL_SENSOR0_16);
            panel6Right.AddRange(PANEL6_MPT2_COOL_SENSOR1_16);
            panel6Right.AddRange(PANEL6_MPT2_COOL_SENSOR2_16);
            panel6Right.AddRange(PANEL6_MPT2_COOL_SENSOR0_64);
            panel6Right.AddRange(PANEL6_MPT2_COOL_SENSOR1_64);
            panel6Right.AddRange(PANEL6_MPT2_COOL_SENSOR2_64);
            panel6Right.AddRange(PANEL6_MPT2_COOL_SENSOR0_128);
            panel6Right.AddRange(PANEL6_MPT2_COOL_SENSOR1_128);
            panel6Right.AddRange(PANEL6_MPT2_COOL_SENSOR2_128);
            panel6Right.AddRange(PANEL6_MPT2_COMBINED_SENSOR0_64);
            panel6Right.AddRange(PANEL6_MPT2_COMBINED_SENSOR1_64);
            panel6Right.AddRange(PANEL6_MPT2_COMBINED_SENSOR2_64);
            user_commentsTag = "SG.CR11.DLECT.PANEL6.MPT2.ANNOTATE_USER_COMMENT";
            stop_session_commentsTag = "SG.CR11.DLECT.PANEL6.MPT2.ANNOTATE_STOP_SESSION";
            return panel6Right.ToArray();
        }

        /// <summary>
        /// Method to add Panel 7 Measurement location Left Point tags to a List
        /// </summary>
        /// <returns></returns>
        public static string[] Panel7Left()
        {
            panel7Left.Clear();
            panel7Left.AddRange(PANEL7_MPT1_WARM_SENSOR0_16);
            panel7Left.AddRange(PANEL7_MPT1_WARM_SENSOR1_16);
            panel7Left.AddRange(PANEL7_MPT1_WARM_SENSOR2_16);
            panel7Left.AddRange(PANEL7_MPT1_WARM_SENSOR0_64);
            panel7Left.AddRange(PANEL7_MPT1_WARM_SENSOR1_64);
            panel7Left.AddRange(PANEL7_MPT1_WARM_SENSOR2_64);
            panel7Left.AddRange(PANEL7_MPT1_WARM_SENSOR0_128);
            panel7Left.AddRange(PANEL7_MPT1_WARM_SENSOR1_128);
            panel7Left.AddRange(PANEL7_MPT1_WARM_SENSOR2_128);
            panel7Left.AddRange(PANEL7_MPT1_COOL_SENSOR0_16);
            panel7Left.AddRange(PANEL7_MPT1_COOL_SENSOR1_16);
            panel7Left.AddRange(PANEL7_MPT1_COOL_SENSOR2_16);
            panel7Left.AddRange(PANEL7_MPT1_COOL_SENSOR0_64);
            panel7Left.AddRange(PANEL7_MPT1_COOL_SENSOR1_64);
            panel7Left.AddRange(PANEL7_MPT1_COOL_SENSOR2_64);
            panel7Left.AddRange(PANEL7_MPT1_COOL_SENSOR0_128);
            panel7Left.AddRange(PANEL7_MPT1_COOL_SENSOR1_128);
            panel7Left.AddRange(PANEL7_MPT1_COOL_SENSOR2_128);
            panel7Left.AddRange(PANEL7_MPT1_COMBINED_SENSOR0_64);
            panel7Left.AddRange(PANEL7_MPT1_COMBINED_SENSOR1_64);
            panel7Left.AddRange(PANEL7_MPT1_COMBINED_SENSOR2_64);
            user_commentsTag = "SG.CR11.DLECT.PANEL7.MPT1.ANNOTATE_USER_COMMENT";
            stop_session_commentsTag = "SG.CR11.DLECT.PANEL7.MPT1.ANNOTATE_STOP_SESSION";
            return panel7Left.ToArray();
        }

        /// <summary>
        /// Method to add Panel 7 Measurement location Right Point tags to a List
        /// </summary>
        /// <returns></returns>
        public static string[] Panel7Right()
        {
            panel7Right.Clear();
            panel7Right.AddRange(PANEL7_MPT2_WARM_SENSOR0_16);
            panel7Right.AddRange(PANEL7_MPT2_WARM_SENSOR1_16);
            panel7Right.AddRange(PANEL7_MPT2_WARM_SENSOR2_16);
            panel7Right.AddRange(PANEL7_MPT2_WARM_SENSOR0_64);
            panel7Right.AddRange(PANEL7_MPT2_WARM_SENSOR1_64);
            panel7Right.AddRange(PANEL7_MPT2_WARM_SENSOR2_64);
            panel7Right.AddRange(PANEL7_MPT2_WARM_SENSOR0_128);
            panel7Right.AddRange(PANEL7_MPT2_WARM_SENSOR1_128);
            panel7Right.AddRange(PANEL7_MPT2_WARM_SENSOR2_128);
            panel7Right.AddRange(PANEL7_MPT2_COOL_SENSOR0_16);
            panel7Right.AddRange(PANEL7_MPT2_COOL_SENSOR1_16);
            panel7Right.AddRange(PANEL7_MPT2_COOL_SENSOR2_16);
            panel7Right.AddRange(PANEL7_MPT2_COOL_SENSOR0_64);
            panel7Right.AddRange(PANEL7_MPT2_COOL_SENSOR1_64);
            panel7Right.AddRange(PANEL7_MPT2_COOL_SENSOR2_64);
            panel7Right.AddRange(PANEL7_MPT2_COOL_SENSOR0_128);
            panel7Right.AddRange(PANEL7_MPT2_COOL_SENSOR1_128);
            panel7Right.AddRange(PANEL7_MPT2_COOL_SENSOR2_128);
            panel7Right.AddRange(PANEL7_MPT2_COMBINED_SENSOR0_64);
            panel7Right.AddRange(PANEL7_MPT2_COMBINED_SENSOR1_64);
            panel7Right.AddRange(PANEL7_MPT2_COMBINED_SENSOR2_64);
            user_commentsTag = "SG.CR11.DLECT.PANEL7.MPT2.ANNOTATE_USER_COMMENT";
            stop_session_commentsTag = "SG.CR11.DLECT.PANEL7.MPT2.ANNOTATE_STOP_SESSION";
            return panel7Right.ToArray();
        }

        /// <summary>
        /// Method to add Panel 8 Measurement location Left Point tags to a List
        /// </summary>
        /// <returns></returns>
        public static string[] Panel8Left()
        {
            panel8Left.Clear();
            panel8Left.AddRange(PANEL8_MPT1_WARM_SENSOR0_16);
            panel8Left.AddRange(PANEL8_MPT1_WARM_SENSOR1_16);
            panel8Left.AddRange(PANEL8_MPT1_WARM_SENSOR2_16);
            panel8Left.AddRange(PANEL8_MPT1_WARM_SENSOR0_64);
            panel8Left.AddRange(PANEL8_MPT1_WARM_SENSOR1_64);
            panel8Left.AddRange(PANEL8_MPT1_WARM_SENSOR2_64);
            panel8Left.AddRange(PANEL8_MPT1_WARM_SENSOR0_128);
            panel8Left.AddRange(PANEL8_MPT1_WARM_SENSOR1_128);
            panel8Left.AddRange(PANEL8_MPT1_WARM_SENSOR2_128);
            panel8Left.AddRange(PANEL8_MPT1_COOL_SENSOR0_16);
            panel8Left.AddRange(PANEL8_MPT1_COOL_SENSOR1_16);
            panel8Left.AddRange(PANEL8_MPT1_COOL_SENSOR2_16);
            panel8Left.AddRange(PANEL8_MPT1_COOL_SENSOR0_64);
            panel8Left.AddRange(PANEL8_MPT1_COOL_SENSOR1_64);
            panel8Left.AddRange(PANEL8_MPT1_COOL_SENSOR2_64);
            panel8Left.AddRange(PANEL8_MPT1_COOL_SENSOR0_128);
            panel8Left.AddRange(PANEL8_MPT1_COOL_SENSOR1_128);
            panel8Left.AddRange(PANEL8_MPT1_COOL_SENSOR2_128);
            panel8Left.AddRange(PANEL8_MPT1_COMBINED_SENSOR0_64);
            panel8Left.AddRange(PANEL8_MPT1_COMBINED_SENSOR1_64);
            panel8Left.AddRange(PANEL8_MPT1_COMBINED_SENSOR2_64);
            user_commentsTag = "SG.CR11.DLECT.PANEL8.MPT1.ANNOTATE_USER_COMMENT";
            stop_session_commentsTag = "SG.CR11.DLECT.PANEL8.MPT1.ANNOTATE_STOP_SESSION";
            return panel8Left.ToArray();
        }

        /// <summary>
        /// Method to add Panel 8 Measurement location Right Point tags to a List
        /// </summary>
        /// <returns></returns>
        public static string[] Panel8Right()
        {
            panel8Right.Clear();
            panel8Right.AddRange(PANEL8_MPT2_WARM_SENSOR0_16);
            panel8Right.AddRange(PANEL8_MPT2_WARM_SENSOR1_16);
            panel8Right.AddRange(PANEL8_MPT2_WARM_SENSOR2_16);
            panel8Right.AddRange(PANEL8_MPT2_WARM_SENSOR0_64);
            panel8Right.AddRange(PANEL8_MPT2_WARM_SENSOR1_64);
            panel8Right.AddRange(PANEL8_MPT2_WARM_SENSOR2_64);
            panel8Right.AddRange(PANEL8_MPT2_WARM_SENSOR0_128);
            panel8Right.AddRange(PANEL8_MPT2_WARM_SENSOR1_128);
            panel8Right.AddRange(PANEL8_MPT2_WARM_SENSOR2_128);
            panel8Right.AddRange(PANEL8_MPT2_COOL_SENSOR0_16);
            panel8Right.AddRange(PANEL8_MPT2_COOL_SENSOR1_16);
            panel8Right.AddRange(PANEL8_MPT2_COOL_SENSOR2_16);
            panel8Right.AddRange(PANEL8_MPT2_COOL_SENSOR0_64);
            panel8Right.AddRange(PANEL8_MPT2_COOL_SENSOR1_64);
            panel8Right.AddRange(PANEL8_MPT2_COOL_SENSOR2_64);
            panel8Right.AddRange(PANEL8_MPT2_COOL_SENSOR0_128);
            panel8Right.AddRange(PANEL8_MPT2_COOL_SENSOR1_128);
            panel8Right.AddRange(PANEL8_MPT2_COOL_SENSOR2_128);
            panel8Right.AddRange(PANEL8_MPT2_COMBINED_SENSOR0_64);
            panel8Right.AddRange(PANEL8_MPT2_COMBINED_SENSOR1_64);
            panel8Right.AddRange(PANEL8_MPT2_COMBINED_SENSOR2_64);
            user_commentsTag = "SG.CR11.DLECT.PANEL8.MPT2.ANNOTATE_USER_COMMENT";
            stop_session_commentsTag = "SG.CR11.DLECT.PANEL8.MPT2.ANNOTATE_STOP_SESSION";
            return panel8Right.ToArray();
        }
    }
}
